[package]
name = "stepsampler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
argh = "0.1.13"
env_logger = "0.11.8"
glob = "0.3.3"
hound = "3.5.1"
itertools = "0.14.0"
log = "0.4.27"
rubato = { version = "0.16.2", features = ["log"] }
