[package]
name = "stepsampler-web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.78"
stepsampler = { version = "0.1.0", path = "../stepsampler" }
wasm-bindgen = "0.2.101"
